# general
gpu_id: 0
use_gpu: True
seed: 2021
state: INFO
reproducibility: False
data_path: 'lcq2data6/'
checkpoint_dir: 'saved_ppspq6/'
generated_text_dir: 'generated_ppspq6/'
plot: True

# training settings
epochs: 150
warmup_epochs: 1
iters_per_epoch: 1000
train_batch_size: 32
learner: adam
learning_rate: 0.0001
eval_step: 1
stopping_step: 3
grad_clip: 1.0

# evaluation settings
eval_batch_size: 50
